Name: FileManager
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/file-manager/
Description: The FileManager app provides an intuitive UI for managing all your files

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com